server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s

app:
  base-url: http://localhost:8080
  storage:
    type: memory
  bigtable:
    project-id: your-gcp-project-id
    instance-id: your-bigtable-instance-id
    link-table: comp-539-team-1-urlmap
    creator-index-table: comp-539-team-1-links-by-creator
    emulator-host:
    emulator-port:
